[hekad]
maxprocs = 4
base_dir = "E:/mabodev/dc/hekad" 
share_dir = "E:/mabodev/dc/hekad/share/heka"

[test_TcpInput]
type = "TcpInput"
address = "0.0.0.0:5567"
parser_type = "regexp"
delimiter = ",|$"
#decoder = "ProtobufDecoder"

[client_log]
type = "LogstreamerInput"
rescan_interval  = "5s"
log_directory = "E:\\mabodev\\mabo.io\\py\\heka"
#file_match = 'heka_tcp.log'
file_match = 'heka_tcp\.log\.?(?P<Seq>\d*)'
priority = ["^Seq"]

[PayloadEncoder]
append_newlines = true
prefix_ts = true
ts_format = "2006/01/02 3:04:05PM MST"

[console_log]
type = "LogOutput"
message_matcher = "TRUE"
encoder = "PayloadEncoder"

[log_file]
type = "FileOutput"
message_matcher = "TRUE"
path = "./heka-test1.log"
#prefix_ts = true
perm = "666"
flush_count = 1
flush_operator = "OR"
encoder = "PayloadEncoder"
