[hekad]
maxprocs = 4
base_dir = "E:/mabodev/dc/hekad" 
share_dir = "E:/mabodev/dc/hekad/share/heka"

[test_TcpInput]
type = "TcpInput"
address = "0.0.0.0:5567"
parser_type = "regexp"
delimiter = ",|$"
#decoder = "ProtobufDecoder"

[client_log]
type = "LogstreamerInput"
rescan_interval  = "5s"
#log_directory = "E:\\mabodev\\mabo.io\\py\\heka"
log_directory = "E:\\mabodev\\mabo.io\\bin"
file_match = 'test_debug.log'
#file_match = 'heka_tcp\.log\.?(?P<Seq>\d*)'
#priority = ["^Seq"]


###

[AMQPOutput]
url = "amqp://guest:guest@localhost:5672/"
exchange = "testout"
exchange_type  = "fanout"
exchange_durability   = true
exchange_auto_delete   = true
routing_key  = "mabo"
#"fanout"
message_matcher = 'TRUE'
encoder = "PayloadEncoder"

[ESJsonEncoder]
index = "%{Type}-%{2006.01.02}"
es_index_from_timestamp = true
type_name = "%{Type}"

[AMQPOutput2]
type = "AMQPOutput"
url = "amqp://guest:guest@localhost:5672/"
exchange = "heka"
exchange_type  = "topic"
exchange_durability   = true
exchange_auto_delete   = true
routing_key  = "hekaq"
#"fanout"
message_matcher = 'TRUE'
encoder = "PayloadEncoder"


[PayloadEncoder]
append_newlines = true
prefix_ts = false
ts_format = "2006/01/02 3:04:05PM MST"

[console_log]
type = "LogOutput"
message_matcher = "TRUE"
encoder = "ESJsonEncoder"

[log_file]
type = "FileOutput"
message_matcher = "TRUE"
path = "./heka-test1.log"
#prefix_ts = true
perm = "666"
flush_count = 1
flush_operator = "OR"
encoder = "PayloadEncoder"
