
[app]

target = "target.png"

camera_uri = "rtsp://192.168.199.24:554"

crop_start = [260,110]

crop_start_x = 180
#(180,250)
crop_start_y = 250

corp_width = 250

throshhold = 20

distance = 25

debug = 1