
[app]

target = "sh2.png"

camera_uri = "rtsp://192.168.1.10:554/user=admin&password=&channel=1&stream=1.sdp?"

crop_start = [230,150]

crop_start_x = 80
#(180,250)
crop_start_y = 150

corp_width = 300

throshhold = 20

distance = 25

debug = 1