

[client]

host = "127.0.0.1"
port = 6010

ticker_interval = 3

max_retry = 5
retry_interval = 3

timeout = 10

#BEP,  MAHA, HORIBA, AVL

equipment = "BEP"
channel_number = 0

non_data_len = 10

[logging]

logfile = "ak_cli.log"
max_size = 102400
backup_count = 5