

[client]

host = "127.0.0.1"
port = 6010

cmd = "AVFI"

cmd_seq = ["AVFI","AVFI"]

seq_interval = 3

ticker_interval = 3

max_retry = 5
retry_interval = 3

timeout = 10

#BEP,  MAHA, HORIBA, AVL

equipment = "BEP"

channel_number = 0

non_data_len = 10

[redis]

redis_host = "127.0.0.1"
redis_port = 4357

[logging]

logfile = "ak_cli.log"

level = "DEBUG"

datetime_format = "local"

max_size = 102400
backup_count = 5



